# Generated by Django 2.2.7 on 2019-12-16 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='设备名称')),
                ('specifications', models.CharField(max_length=64, verbose_name='规格型号')),
                ('device_type', models.CharField(max_length=128, verbose_name='设备类型')),
                ('status', models.SmallIntegerField(choices=[(0, '正常'), (1, '故障'), (2, '备用')], default=0, verbose_name='设备状态')),
                ('manufacturer', models.CharField(max_length=64, verbose_name='生产厂家')),
                ('distributor', models.CharField(max_length=64, verbose_name='供应商')),
                ('purchase_time', models.DateTimeField(verbose_name='购买时间')),
                ('use_time', models.DateTimeField(verbose_name='启用时间')),
                ('number', models.CharField(max_length=64, verbose_name='设备编号')),
                ('parameter', models.TextField(verbose_name='设备参数')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
            },
        ),
        migrations.CreateModel(
            name='ManufacturingShop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='车间名称')),
            ],
            options={
                'verbose_name': '车间信息',
                'verbose_name_plural': '车间信息',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('number', models.CharField(max_length=64, verbose_name='人员编号')),
                ('duty', models.CharField(max_length=64, verbose_name='职务')),
            ],
            options={
                'verbose_name': '工作人员信息',
                'verbose_name_plural': '工作人员信息',
            },
        ),
        migrations.CreateModel(
            name='Upkeep',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(verbose_name='日期')),
                ('results', models.TextField(verbose_name='保养工单')),
                ('status', models.TextField(verbose_name='保养内容')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='保养设备')),
                ('worker', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='equipment.Worker', verbose_name='保养人员')),
            ],
            options={
                'verbose_name': '保养信息',
                'verbose_name_plural': '保养信息',
            },
        ),
        migrations.CreateModel(
            name='Maintain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(verbose_name='日期')),
                ('results', models.TextField(verbose_name='维修工单')),
                ('status', models.TextField(verbose_name='故障原因')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='维修设备')),
                ('worker', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='equipment.Worker', verbose_name='维修人员')),
            ],
            options={
                'verbose_name': '维修信息',
                'verbose_name_plural': '维修信息',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(verbose_name='日期')),
                ('results', models.SmallIntegerField(choices=[(0, '正常'), (1, '异常')], default=0, verbose_name='结果')),
                ('status', models.SmallIntegerField(choices=[(0, '正常运行'), (1, '停用')], default=0, verbose_name='设备状态')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='巡检设备')),
                ('worker', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='equipment.Worker', verbose_name='巡检人员')),
            ],
            options={
                'verbose_name': '巡检信息',
                'verbose_name_plural': '巡检信息',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='director',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='equipment.Worker', verbose_name='设备管理人'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='site',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='equipment.ManufacturingShop', verbose_name='安装地点'),
        ),
    ]
